# Rust formatting configuration
# See: https://rust-lang.github.io/rustfmt/

edition = "2024"
max_width = 100
use_small_heuristics = "Default"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
